services:
  spring-backend:
    build: "./spring-backend"
    container_name: "spring-backend"
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DB=${MYSQL_DB}
      - AUTH_KEY=${AUTH_KEY}
    ports:
      - 80:80